### ISSUE TITLE
make errors

### ISSUE THREAD

**Issue by izengpan** [LRMPUT/PlaneLoc#1]
hello, thanks for your great work.
I followed your steps to build the project.
But when I use the "make" instruction, two errors occured, and I can't find the solution. They are the same problem to two functions, convertToPointsDirsDists() and bestTransformPointsDirsDists().

Tests.cpp:263:88: error: no matching function for call to ‘Matching::bestTransformPointsDirsDists(std::vector<Eigen::Matrix<double, 3, 1> >&, std::vector<Eigen::Matrix<double, 3, 1> >&, std::vector<double>, std::vector<Eigen::Matrix<double, 3, 1> >&, std::vector<Eigen::Matrix<double, 3, 1> >&, std::vector<double>, std::vector<Eigen::Matrix<double, 3, 1> >&, std::vector<Eigen::Matrix<double, 3, 1> >&, std::vector<double>, std::vector<double>&, std::vector<double>&, std::vector<Eigen::Matrix<double, 3, 1> >&, std::vector<double>, std::vector<Eigen::Matrix<double, 3, 1> >&, std::vector<Eigen::Matrix<double, 3, 1> >&, std::vector<Eigen::Matrix<double, 3, 1> >&, std::vector<double>, double&, bool&, bool&)’
                                                                     fullConstrTransComp);
                                        

and 

/Tests.cpp:239:43: error: no matching function for call to ‘Matching::convertToPointsDirsDists(std::vector<Eigen::Matrix<double, 3, 1> >&, std::vector<Eigen::Matrix<double, 4, 1> >&, std::vector<Eigen::Matrix<double, 6, 1, 0> >&, std::vector<Eigen::Matrix<double, 3, 1> >&, std::vector<Eigen::Matrix<double, 3, 1> >&, std::vector<Eigen::Matrix<double, 3, 1> >&, std::vector<double>&, std::vector<Eigen::Matrix<double, 3, 1> >&, std::vector<Eigen::Matrix<double, 3, 1> >&, std::vector<Eigen::Matrix<double, 3, 1> >&)’
                        retTransDistPtsDirs);

**Comment by jwietrzykowski** [comment]
Hi,

I've pushed update with disabled compilation for obsolete test code. It should compile correctly now.

Best regards

**Comment by izengpan** [comment]
thanks for your kind reply.
The problem has been solved. And I make it successfully.
But, when I attempt to use fr1 dataset to Launch the demo, error occurs.

terminate called after throwing an instance of 'plane_exception'
  what():  Exception 'pgm_exception' thrown in file '/home/zp/PlaneLoc/src/FileGrabber.cpp' line '262' with message:
Cannot read depth file /home/zp/PlaneLoc/build


I have checked the path, and cout the path, it seems that everything is right. And the last depth images can be readed.
Do you have any ideas?

**Comment by izengpan** [comment]
And each time, when I "make"  the project, the whole process will  be very long, besides, my computer also will be stucked when "make".
Have you met this problem before?
Thanks!

**Comment by jwietrzykowski** [comment]
Maybe your images are in a wrong directories. They should be in separate _rgb_ and _depth_ folders inside directory specified in settings file. Take a look at the code in the constructor of _FrameGrabber_ and you will deduce what the proper organization of data in dataset should be.

**Comment by izengpan** [comment]
I have put the dataset in the right place, 

![image](https://user-images.githubusercontent.com/33143024/57971452-0588a100-79c1-11e9-9738-18605835b487.png)

![image](https://user-images.githubusercontent.com/33143024/57971456-0faa9f80-79c1-11e9-9a4a-9dce7e8d7c94.png)

And I print the image name when it read the image successfully.
the problem is that the final depth image can't be read.
it's so weird.

![image](https://user-images.githubusercontent.com/33143024/57971487-7334cd00-79c1-11e9-844d-87cffeb20cdc.png)

In this picture, I print whether the ifempty=rgb.empty(), and ifempty1=depth.empty() .
they always be 0. except the last depth frame. you can see in the picture, it is 1.and error occurs.
