### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by izengpan** [LRMPUT/PlaneLoc#2]
when I attempt to use fr1 dataset to Launch the demo, error occurs.

terminate called after throwing an instance of 'plane_exception'
what(): Exception 'pgm_exception' thrown in file '/home/zp/PlaneLoc/src/FileGrabber.cpp' line '262' with message:
**Cannot read depth file** /home/zp/PlaneLoc/build

I have checked the path, and cout the path, it seems that everything is right. And the last depth images can be read.

And  for the final depth image:  **depth.empty()**=true, in the **PlaneLoc/src/FileGrabber.cpp**

Do you have any ideas?

**Comment by jwietrzykowski** [comment]
It looks like the path for depth image in invalid (/home/zp/PlaneLoc/build is for sure not a valid path). Is there equal number of RGB and depth images? Could you send a list of files in _rgb_ and _depth_ directories as a text file and settings file?

**Comment by izengpan** [comment]
You're right. I have checked the picture number of the freiburg1_room, and the number of depth picture and rgb picture is not the same, I have solved it before your reply. I dropped the final 2 pictures of rgb, and it worked.

However, life is always amazing. the final output of the console is very strange. 
![image](https://user-images.githubusercontent.com/33143024/58061031-e481a500-7ba6-11e9-899c-d4872c11ab38.png)

And there is nothing in the 3D viewer.
![image](https://user-images.githubusercontent.com/33143024/58061057-0a0eae80-7ba7-11e9-9eb4-c061f937f1c6.png)

I guess maybe because the timestamps is not matched between these two series. What's your opinion.

**Comment by izengpan** [comment]
[depth.txt](https://github.com/LRMPUT/PlaneLoc/files/3200315/depth.txt)
[rgb.txt](https://github.com/LRMPUT/PlaneLoc/files/3200316/rgb.txt)
this is the origin list of files in rgb and depth directories. 
I delete the final 2 lines:
1305031956.104901 rgb/1305031956.104901.png
1305031956.136924 rgb/1305031956.136924.png

**Comment by izengpan** [comment]
I have found the problem, these problem all caused by incomplete  input files. Such as 
map.ply、instance、labels、accelDataAll、groundtruth、voAll、voCorrAll.

Now I only have the freiburg1_room dataset. Can you give an example of the full input file in the res directory?

really thanks.

**Comment by jwietrzykowski** [comment]
You need only _groundtruth.txt_ and _vo.txt_ files (see format in attachment). The _vo.txt_ file can be generated using any visual odometry algorithm, e.g. ORB SLAM2 without loop closure. Accumulated representation files can be generated by setting "processFrames: 0" in settings file. You will need one or more files with the map of the whole environment (adjust _accFrames_ variable to cover the whole sequence used to generate the map) and separate files for each frame you want to perform localization for (I accumulated 50 consecutive frames for each localization act).

[groundtruth.txt](https://github.com/LRMPUT/PlaneLoc/files/3222584/groundtruth.txt)
[vo.txt](https://github.com/LRMPUT/PlaneLoc/files/3222585/vo.txt)

**Comment by jyakaranda** [comment]
> You need only _groundtruth.txt_ and _vo.txt_ files (see format in attachment). The _vo.txt_ file can be generated using any visual odometry algorithm, e.g. ORB SLAM2 without loop closure. Accumulated representation files can be generated by setting "processFrames: 0" in settings file. You will need one or more files with the map of the whole environment (adjust _accFrames_ variable to cover the whole sequence used to generate the map) and separate files for each frame you want to perform localization for (I accumulated 50 consecutive frames for each localization act).
> 
> [groundtruth.txt](https://github.com/LRMPUT/PlaneLoc/files/3222584/groundtruth.txt)
> [vo.txt](https://github.com/LRMPUT/PlaneLoc/files/3222585/vo.

Hello, I downloaded [seq1](https://drive.google.com/open?id=0B_h9nxEvyL2wVDhuOFp3X1dPN2M) from [dataset](http://lrm.put.poznan.pl/rgbdw/) you provide, generated [vo.txt](https://github.com/LRMPUT/PlaneLoc/files/4515975/vo.txt) using ORB_SLAM2, and modified [settings.yaml](https://github.com/LRMPUT/PlaneLoc/files/4516018/settings.txt). But the PlaneLoc is still not work as wish, output nothing in viewer. And output in console is:
```reading rgb images paths
reading depth images paths
reading clouds paths
reading acc paths
reading pose data
reading VO data
setting nextFrameIdx
object instances in map: 0
cameraParams = [537.40869, 0, 320.37619;
 0, 537.48358, 235.9355;
 0, 0, 1]
gtOffsetSE3Quat = 0 0 0 0 0 0 1
Getting object instances from map
skipping 850 frames
reading global settings
Starting the loop
curFrameIdx = 850
timestamp = 28333333
...
```
I noticed that there's no object instance in map, maybe this is the cause. Could you please give more suggestions to launch the demo using dataset you provide? Thank you.

**Comment by jiashoujun** [comment]
I meet the same problem with you. Have you solved it?

**Comment by jwietrzykowski** [comment]
You have to build instance maps first by accumulating frames from the whole trajectory (set `accFrames` to the length of the trajectory) and point to those files in _settings.yml_ (map/mapFiles).
