### ISSUE TITLE
PUT Dataset

### ISSUE THREAD

**Issue by richard5635** [LRMPUT/PlaneLoc#3]
Hi, I am not sure if it is okay to place this in an issue, but I cannot access the website to download the PUT dataset. Is there another source where I can download the dataset from?
Thanks!

http://www.vision.put.poznan.pl/?cat=16

**Comment by jwietrzykowski** [comment]
Hi,

I've added the link (http://lrm.put.poznan.pl/rgbdw/) to the dataset in readme.

Best regards,
Jan Wietrzykowski

**Comment by richard5635** [comment]
Thanks!

**Comment by jiashoujun** [comment]
Hi, thanks for your important work.
I followed your work to build the project.
But when I use the PUT dataset, one error occured, and I can't find the solution. 
the demo can not read the map data, named cloud_merged.ply. 
The error is 
"terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error
Aborted (core dumped)"
Could you give me some suggestions?

**Comment by jwietrzykowski** [comment]
_cloud_merged.ply_ is the old format of the map. Use accumulated instance maps from the whole trajectories (those you want to use as the map) - described here: https://github.com/LRMPUT/PlaneLoc/issues/2#issuecomment-496129859

**Comment by jiashoujun** [comment]
Thanks for your comments! I thank that your work is significant for high-accuracy visual SLAM, especially for the complex environment with changing illumination and low texture. The problem of global map has been bothering me for a week. Recently, I have used the groundtruth.txt, and tried to build the instance maps, but I don't know how to adjust the settings.yml for generating the instance maps. Moreover, I cannot find the parameter, named accFrames in settings.yml. could you give me more details? Thank you!

**Comment by jwietrzykowski** [comment]
I've added `accFrames` to settings file and updated README with instructions how generate your own maps.

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!

**Comment by jiashoujun** [comment]
Thanks for very much! I have made it clear after your comments, and can install your project. However, when I run the demo, I meet the mistake as follows: 

*** Error in `/home/jsj/jsj/jsj_project/PlaneLoc-master/build/demoPlaneSlam': double free or corruption (out): 0x00007f269e74e020 ***
======= Backtrace: =========
......
======= Memory map: ========
......
What I can determine is that the error can be located in   if (processFrames) { ... }   in PlaneSlam.cpp. Could you give me some advice? Thank you!
