### ISSUE TITLE
Launch demo

### ISSUE THREAD

**Issue by shumingcong** [LRMPUT/PlaneLoc#4]
Hello, i cannot find file called demoPlaneSlam.cpp ,  and in demos file just the cppfile called demoSlam.cpp. The demoSlam.cpp is launch demo ? 
Thanks.

**Comment by jwietrzykowski** [comment]
Hi,

yes, _demoSlam.cpp_ is a main .cpp file for demo. Executable should be named _demoPlaneSlam_.

Best regards
